

from __future__ import annotations

import argparse
import os
import re
import time
from pathlib import Path

from google import genai
from google.genai import errors as genai_errors
from google.genai import types
from dotenv import load_dotenv


DEFAULT_PROMPTS_PATH = (
    "outputs\wheels on the bus\prompts\rhyme_and_scene_prompts.txt"
)
DEFAULT_OUTPUT_ROOT = "outputs"
DEFAULT_VEO_MODEL = "veo-3.1-generate-preview"
DEFAULT_EXTENSION_READY_RETRIES = 6
DEFAULT_EXTENSION_READY_DELAY_SECONDS = 15


def _parse_scene_prompts(file_path: Path) -> list[str]:
    if not file_path.exists():
        raise FileNotFoundError(f"Prompt file not found: {file_path}")

    lines = file_path.read_text(encoding="utf-8").splitlines()
    prompts: list[str] = []
    for line in lines:
        match = re.match(r"^\s*Visual Prompt:\s*(.+)\s*$", line)
        if match:
            prompts.append(match.group(1).strip())

    if not prompts:
        raise ValueError(f"No 'Visual Prompt:' lines found in: {file_path}")
    return prompts


def _get_api_key_from_env() -> str:
    candidates = [
        os.getenv("GEMINI_API_KEY", "").strip(),
        os.getenv("GOOGLE_API_KEY", "").strip(),
        os.getenv("VEO_API_KEY", "").strip(),
    ]
    api_key = next((value for value in candidates if value), "")
    if not api_key:
        raise RuntimeError(
            "Missing API key. Set GEMINI_API_KEY (or GOOGLE_API_KEY / VEO_API_KEY) in .env."
        )
    return api_key


def _validate_extension_model(model: str) -> None:
    model_lower = model.lower()
    if "lite" in model_lower:
        raise ValueError(
            f"Model '{model}' does not support Veo video extension reliably. "
            f"Use '{DEFAULT_VEO_MODEL}' or another non-lite Veo 3/3.1 generate model."
        )
    if "veo" not in model_lower:
        raise ValueError(
            f"Model '{model}' is not a Veo model. Use '{DEFAULT_VEO_MODEL}' for extension."
        )


def _wait_for_video_operation(
    client: genai.Client,
    operation: types.GenerateVideosOperation,
    poll_seconds: int,
    timeout_seconds: int,
) -> types.GenerateVideosOperation:
    start_ts = time.time()
    while not operation.done:
        elapsed = int(time.time() - start_ts)
        if elapsed > timeout_seconds:
            raise TimeoutError("Timed out waiting for Veo video operation.")
        print(f"Waiting for Veo operation... {elapsed}s elapsed")
        time.sleep(poll_seconds)
        operation = client.operations.get(operation)

    if not operation.response or not operation.response.generated_videos:
        raise RuntimeError("Veo operation completed without generated video output.")
    return operation


def _generate_video(
    client: genai.Client,
    model: str,
    prompt: str,
    duration_seconds: int,
    aspect_ratio: str,
    poll_seconds: int,
    timeout_seconds: int,
    source_video: types.Video | None = None,
    extension_ready_retries: int = DEFAULT_EXTENSION_READY_RETRIES,
    extension_ready_delay_seconds: int = DEFAULT_EXTENSION_READY_DELAY_SECONDS,
) -> types.Video:
    config = types.GenerateVideosConfig(
        number_of_videos=1,
        duration_seconds=duration_seconds,
        resolution="720p",
        aspect_ratio=aspect_ratio,
    )
    attempt = 0
    while True:
        try:
            operation = client.models.generate_videos(
                model=model,
                prompt=prompt,
                video=source_video,
                config=config,
            )
            break
        except genai_errors.ClientError as exc:
            message = str(exc)
            message_lower = message.lower()
            if "429" in message and "spending cap" in message_lower:
                raise RuntimeError(
                    "Gemini API rejected video generation because your project monthly spending cap "
                    "is reached. Increase/reset project cap at https://ai.studio/spend, or switch to "
                    "another API key/project with available quota."
                ) from exc

            not_processed_yet = (
                source_video is not None
                and "400" in message
                and "generated by veo" in message_lower
                and "processed" in message_lower
            )
            if not_processed_yet and attempt < extension_ready_retries:
                attempt += 1
                wait_seconds = extension_ready_delay_seconds * attempt
                print(
                    f"Source video not processed yet by Veo. "
                    f"Retrying extension in {wait_seconds}s "
                    f"({attempt}/{extension_ready_retries})..."
                )
                time.sleep(wait_seconds)
                continue
            raise
    operation = _wait_for_video_operation(
        client=client,
        operation=operation,
        poll_seconds=poll_seconds,
        timeout_seconds=timeout_seconds,
    )
    return operation.response.generated_videos[0].video


def _sanitize_for_dir(name: str) -> str:
    cleaned = re.sub(r"[<>:\"/\\|?*\x00-\x1F]", "", name)
    cleaned = re.sub(r"\s+", " ", cleaned).strip()
    cleaned = cleaned.rstrip(".")
    return cleaned[:80] if cleaned else "untitled_video"


def _infer_video_title_from_prompts_file(prompts_file: Path) -> str:
    prompts_dir = prompts_file.parent
    if prompts_dir.name == "prompts":
        return prompts_dir.parent.name
    return prompts_dir.name


def _build_output_dir(root: Path, video_title: str) -> Path:
    target = root / video_title / "video_clips"
    target.mkdir(parents=True, exist_ok=True)
    return target


def main() -> None:
    load_dotenv()

    parser = argparse.ArgumentParser(description="Generate and extend Veo videos from scene prompts")
    parser.add_argument("--prompts-file", type=str, default=DEFAULT_PROMPTS_PATH)
    parser.add_argument("--output-root", type=str, default=DEFAULT_OUTPUT_ROOT)
    parser.add_argument("--model", type=str, default=os.getenv("VEO_MODEL", DEFAULT_VEO_MODEL))
    parser.add_argument("--initial-seconds", type=int, default=8)
    parser.add_argument("--target-seconds", type=int, default=56)
    parser.add_argument("--extend-step-seconds", type=int, default=8)
    parser.add_argument("--aspect-ratio", type=str, default=os.getenv("VEO_ASPECT_RATIO", "9:16"))
    parser.add_argument("--poll-seconds", type=int, default=int(os.getenv("VEO_POLL_SECONDS", "10")))
    parser.add_argument("--timeout-seconds", type=int, default=int(os.getenv("VEO_TIMEOUT_SECONDS", "1800")))
    parser.add_argument(
        "--extension-ready-retries",
        type=int,
        default=int(os.getenv("VEO_EXTENSION_READY_RETRIES", str(DEFAULT_EXTENSION_READY_RETRIES))),
    )
    parser.add_argument(
        "--extension-ready-delay-seconds",
        type=int,
        default=int(
            os.getenv(
                "VEO_EXTENSION_READY_DELAY_SECONDS",
                str(DEFAULT_EXTENSION_READY_DELAY_SECONDS),
            )
        ),
    )
    args = parser.parse_args()
    _validate_extension_model(args.model)

    if args.initial_seconds != 8:
        print(
            f"Initial generation requested {args.initial_seconds}s. "
            "For Veo extension stability, forcing initial duration to 8s."
        )
        args.initial_seconds = 8

    if args.extend_step_seconds != 8:
        print(
            f"Extension step requested {args.extend_step_seconds}s. "
            "Veo extension requires 8s chunks; forcing extend step to 8s."
        )
        args.extend_step_seconds = 8

    prompts_file = Path(args.prompts_file)
    video_title = _sanitize_for_dir(_infer_video_title_from_prompts_file(prompts_file))
    output_dir = _build_output_dir(Path(args.output_root), video_title)
    scene_prompts = _parse_scene_prompts(prompts_file)

    api_key = _get_api_key_from_env()
    client = genai.Client(api_key=api_key)

    print(f"Loaded {len(scene_prompts)} scene prompts from: {prompts_file}")
    print(f"Using model: {args.model}")
    print(f"Output directory: {output_dir}")

    current_seconds = args.initial_seconds
    prompt_index = 0

    print(f"Generating initial {args.initial_seconds}s clip...")
    current_video = _generate_video(
        client=client,
        model=args.model,
        prompt=scene_prompts[prompt_index],
        duration_seconds=args.initial_seconds,
        aspect_ratio=args.aspect_ratio,
        poll_seconds=args.poll_seconds,
        timeout_seconds=args.timeout_seconds,
        extension_ready_retries=args.extension_ready_retries,
        extension_ready_delay_seconds=args.extension_ready_delay_seconds,
    )
    client.files.download(file=current_video)
    initial_path = output_dir / "step_00_initial.mp4"
    current_video.save(str(initial_path))
    print(f"Saved initial clip: {initial_path}")

    step = 1
    while current_seconds < args.target_seconds:
        prompt_index = (prompt_index + 1) % len(scene_prompts)
        next_prompt = scene_prompts[prompt_index]
        print(
            f"Extending video (step {step}) by {args.extend_step_seconds}s "
            f"toward {args.target_seconds}s target..."
        )
        current_video = _generate_video(
            client=client,
            model=args.model,
            prompt=next_prompt,
            duration_seconds=args.extend_step_seconds,
            aspect_ratio=args.aspect_ratio,
            poll_seconds=args.poll_seconds,
            timeout_seconds=args.timeout_seconds,
            source_video=current_video,
            extension_ready_retries=args.extension_ready_retries,
            extension_ready_delay_seconds=args.extension_ready_delay_seconds,
        )
        client.files.download(file=current_video)
        step_path = output_dir / f"step_{step:02d}_extended.mp4"
        current_video.save(str(step_path))
        print(f"Saved extended clip: {step_path}")

        current_seconds += args.extend_step_seconds
        step += 1

    final_path = output_dir / f"final_{args.target_seconds}s.mp4"
    current_video.save(str(final_path))
    print(f"Final video saved: {final_path}")
    print("Done.")


if __name__ == "__main__":
    main()
